import { ReactNode } from 'react'

import type { Metadata } from 'next'

import { Roboto } from 'next/font/google'

import './globals.css'

import { Providers } from './providers'

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Comedy Portal',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en" className="h-full">
            <body className={`${roboto.variable} h-full bg-gray-50! antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
