import { ReactNode } from 'react'

import type { Metadata } from 'next'

import { Roboto } from 'next/font/google'

import { Footer } from '@/components/features/layout/footer/footer'
import { Header } from '@/components/features/layout/header/header'
import { TailwindIndicator } from '@/components/ui/tailwind-indicator'

import './globals.css'

import { Providers } from './providers'

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Comedy Portal',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en" className="h-full">
            <body className={`${roboto.variable} h-full bg-[#f5f6f7] antialiased`}>
                <Providers>
                    <div className="flex min-h-screen flex-col">
                        <Header />
                        <main className="flex-1">{children}</main>
                        <Footer />
                    </div>
                </Providers>
                <TailwindIndicator />
            </body>
        </html>
    )
}
