import type { Metadata } from 'next'

import { Roboto } from 'next/font/google'

import { ReduxProvider } from '@/redux/provider'
import { SuperTokensInit } from '@/utils/supertokens/supertokens-init'

import './globals.css'

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Comedy Portal',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="h-full">
            <SuperTokensInit>
                <body className={`${roboto.variable} h-full antialiased`}>
                    <ReduxProvider>{children}</ReduxProvider>
                </body>
            </SuperTokensInit>
        </html>
    )
}
